name: martyr_system
description: نظام الشهداء - ذاكرة الوفاء
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.2
  file_picker: ^10.3.8
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
